travis:
  secure:
    BINSTAR_TOKEN: juVctIdvsqPtTP1/q//2AdukbxW7edHSjoJt9NI1WivXiPgSoVM+aIAGfKJ2tV3Pn6xYY7FR1yFOgYMZ/Mpc7OeJZtXjqNG5Q5cjySmnUbECHKIsu/1uQc3JP819xbeFLPAzF+bdcXW2TysHmdW06YrFNb+EU/DlDI3U6fSasCwRvWON0B+bZcm2Gol+hkUY860sibRgfKQ1iRY9dcwfpL+hlAXdifKJB3LG7HcGyI4N1JaojOqGknJ91joRyeLytYEVGTkHMnpoa/AoTXN4kvItJqBupmyIPg/uyflgeU5U0XgLGnQBZmJnoqv2wn+cPGaJrYI6rjx/XitO4myYimoh5e600l/wtTiVL1zmSd2S4qsxbD/E4fzxtq0ZFWS88PrSqQRINtRFRyX3wFXmwmuNdyKSoG12yw9t8BNqtW7MDLNM6mqbNJJLeZwiPTyXVEgKpYeC9Unj0Y8JpVjx6UWKP+6prdJW5mmnqdCcQn9T9tQLwgoAiIFDltHNemUAHsUcA79VkngVt7EJy9KnpBnoTNFX06cRHZv4mrXBBrscH4orFCdoGOkqNv2F78P3bnHHVU6VKlQcyUgivuNOESci7lDCIfomUFd5uyVI4/uG/O5LXspkh+TGYaMlb59Gf3UcG9RfTNXgBT5xnGvv5RvMvklJpYoN23P6OysIuP4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
