travis:
  secure:
    BINSTAR_TOKEN: zvdRt50/kY+Qvrf5MOPitKFB3cA/cw8++V4p8shRQ/VuwkFQ56oh7NJ/uFNOIFTcTLznhXxAHQchtYNiIP7VoBrc/GopsXVa9jRZihqVBBzlfGayc4noiVDIJnm5pSYSp+vOkRz5KyhTBZbzzY1lWTxl4+C5tmhx/GF9PQjdw6nMdpXZnCSLU4RKIYiYsEkXHP8lQelTyJfL+1V8Y4zieFvQfLy1ekHXr002FLVME95jo4AeCvy4s7dmbFBwHE4Us6ok4idsokAq0ii5R6rt/3yweCOEptZhPcMy3+UX1stoIT2NkCuGLBasIMfC4w6l3exsSLKOjdoze5lEtrW/zvPadnYyHb6ZSgft/q9lGBZPF64vm+StKDovb/3ywwL30zwXQZ6GgAiMOmhUJjAUdJnJAmkcoypRZs95p8E4CdxnHTo/jmO3Lkn5tOchiuyUXSAgw9E6rxIz3iSHGXm9ZzYW9UxhUVS+4imGrSWGRMHRH8xRqvhMAh+NhC2i98cYvq9J2vAkcX9qjyPYZtl7Zg6b6DNzBaFmsDS+Oz9uFXiFZk2vMEhN6d0llLc6T+NJVNpfxJY//tpoVmQDIOgngHuxc8Ad/ToWU7EKd8mnrCkAYqN/T4iRg5t6OcARTeE824yGGds0y92q/IU0qsM5iLBL+YoI3hE5tp6WdZrSHaM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
